### PR TITLE
[BREAKING CHANGE] feat: Add Venmo tokenization flow and migrate Android SDK to v5.2.0

### PR DESCRIPTION
**Pull request by iacop0**
**Motivation**
I need the Venmo flow exposed from the library

**Modification**
I add the function `requestVenmoNonce` in the library interface.

For iOS I imported the missing pod `Braintree/Venmo` following the same code style of the existing codebase and I add the missing config plugin.

For Android unfortunately I couldn't use the current version of the SDK since we can't setup an activity lifecycle listener in a button handler. So I migrate all the library to the version v5.2.0 that use the new launcher option.
For that I needed to write some additional config plugin to make the needed setup change.

The Android upgrade brings also a breaking change on the PayPal flow. I follow the official [migration guide](https://github.com/braintree/braintree_android/blob/main/v5_MIGRATION_GUIDE.md) and as mention [there](https://github.com/braintree/braintree_android/blob/main/v5_MIGRATION_GUIDE.md#paypal)

> The PayPal integration now requires an Android App link be configured to return to your app from the PayPal flow. See the [App Link Setup Guide](https://github.com/braintree/braintree_android/blob/main/APP_LINK_SETUP.md) for more information. 

now we need to pass an additional `Merchant App Link` parameter.

I hope this change will ease as well the 3DS implementation :D

### CODE REVIEW

**Comment by msasinowski** [comment]
All of those changes looks really well @iacop0  good job, changes on Android for new SDK look similar to the changes that I made in draft MR's  for 3DSecure.

We need to, update the readme and provide some documentation on how to setup the appLinks since it also requires a change on the Braintree settings.

**Comment by iacop0** [comment]
Cool. Let me know if I should add the README update directly to this PR.

**Comment by fomichova** [comment]
Hi @msasinowski @iacop0!  I'm receiving [Error: TOKENIZE_VAULT_PAYMENT_ERROR] in the requestVenmoNonce response, while I have a valid clientToken, could you please clarify what this could be the error?

**Comment by msasinowski** [comment]
I can take a look, but the best will be to wait for @iacop0 

Is that on Android or IOS ? 
Do you follow the initial steps to integrate Venmo client from braintree page?

**Comment by iacop0** [comment]
That error is [returned](https://github.com/msasinowski/react-native-expo-braintree/blob/5b09459cbcbd16629fc24a8fddbaf647ec75400e/ios/ExpoBraintree.swift#L270) when you don't have a nonce but you have a BTVenmoError.
[These](https://github.com/braintree/braintree_ios/blob/652e69697d4449de5fe509fed5dcafde9f07c1b7/Sources/BraintreeVenmo/BTVenmoError.swift#L29) are all the possible errors you can receive from the SDK. Let me know if it helps

**Comment by fomichova** [comment]
@msasinowski Thanks! It's IOS. I was using your library for PayPal and it worked fine for me, and now I just upgraded it to 3.0.4 to use it for Venmo, should I do something more for this?
@iacop0 Thanks! How can I check what exact error I received from [These](https://github.com/braintree/braintree_ios/blob/652e69697d4449de5fe509fed5dcafde9f07c1b7/Sources/BraintreeVenmo/BTVenmoError.swift#L29) because I'm seeing only TOKENIZE_VAULT_PAYMENT_ERROR and I'm not sure what the exact reason.

**Pull request merged**
